var actionTypes = {
    SET_APP_ROUTE: 'SET_APP_ROUTE',
    GET_SAMPLE_POSTS: 'GET_SAMPLE_POSTS',
    SET_SAMPLE_POSTS: 'SET_SAMPLE_POSTS',
    INCREMENT_SEGMENT_COUNTER: 'INCREMENT_SEGMENT_COUNTER',
    DECREMENT_SEGMENT_COUNTER: 'DECREMENT_SEGMENT_COUNTER'
}

export default actionTypes;
